baseURL = "https://JackTheMico.github.io"
languageCode = "zh-Hans"
defaultContentLanguage = "zh"
title = "Jack Deng 的博客"
theme = "dream"

copyright = '<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img alt="知识共享许可协议" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png" /></a><br />本作品采用<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">知识共享署名-非商业性使用-相同方式共享 4.0 国际许可协议</a>进行许可。'

googleAnalytics = "UA-98295641-1"

disqusShortname = "g1eny0ung"

enableRobotsTXT = true

hasCJKLanguage = true

# https://gohugo.io/news/0.60.0-relnotes/
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[taxonomies]
  tag = "tags"
  category = "categories"

[params]
  # background = "black"
  backgroundImage = "/img/2.jpg"
  linkColor = "seagreen"

  author = "Jack Deng"
  description = "Jack Deng 的生活、技术、杂想记录～"
  avatar = "/img/avatar.jpg"
  motto = "成功不是你赢过多少人，而是你帮过多少人"

  email = "dlwxxxdlw@163.com"
  twitter = ""
  facebook = ""
  instagram = ""
  linkedin = ""
  github = "JackTheMico"
  stackoverflow = "7083162/jack-the-mico"
  codepen = ""

  siteStartYear = 2020

  favicon = "/favicon.ico"

  # dark mode
  darkLinkColor = "darkseagreen"
  darkNav = true
  dark404Button = true
